"""Tests for AICoach pace helpers, km splits, plan parsing, and new tools."""

from unittest.mock import MagicMock, patch

import pandas as pd
import pytest

from strava.utils.ai_coach import (
    AICoach,
    _fmt_pace,
    _fmt_duration,
    _pace_from_speed_ms,
    _pace_from_time_dist,
)


# ── Shared formatting helper tests ──────────────────────────────────


def test_fmt_pace_round():
    """6.0 min/km should format as 6:00/km."""
    assert _fmt_pace(6.0) == "6:00/km"


def test_fmt_pace_fractional():
    """7:22/km at (2877s / 6503m)."""
    pace = (2877 / 60) / (6503 / 1000)
    result = _fmt_pace(pace)
    assert result == "7:22/km"


def test_pace_from_speed_ms_known():
    """Speed → pace should be consistent with _fmt_pace of (1/speed)*1000/60."""
    speed = 2.5  # m/s  → pace = 1000 / (2.5 * 60) = 6.6666... min/km = 6:40/km
    assert _pace_from_speed_ms(speed) == "6:40/km"


def test_pace_from_speed_ms_zero():
    """Zero speed should return 'N/A'."""
    assert _pace_from_speed_ms(0) == "N/A"


def test_pace_from_time_dist_known():
    """2877 s over 6503 m should give 7:22/km."""
    assert _pace_from_time_dist(2877, 6503) == "7:22/km"


def test_pace_from_time_dist_zero_dist():
    """Zero distance should return 'N/A'."""
    assert _pace_from_time_dist(300, 0) == "N/A"


def test_pace_from_time_dist_zero_time():
    """Zero time should return 'N/A'."""
    assert _pace_from_time_dist(0, 5000) == "N/A"


def test_fmt_duration_sub_hour():
    """47m 57s should be 47:57."""
    assert _fmt_duration(2877) == "47:57"


def test_fmt_duration_over_hour():
    """3h 1m 5s."""
    assert _fmt_duration(3600 + 65) == "1:01:05"


def test_fmt_duration_exact_minutes():
    """30 minutes exactly."""
    assert _fmt_duration(1800) == "30:00"


# ── km splits (static helper) tests ────────────────────────────────


def _make_stream_rows(km_times_s: list, hr_base: int = 150):
    """
    Build synthetic stream rows for testing _km_bucket_stats.

    km_times_s: list of seconds each km takes, e.g. [442, 460] → 7:22/km, 7:40/km.
    One row per second, distance ticks at constant rate.
    """
    rows = []
    elapsed = 0.0
    dist = 0.0
    for km_idx, km_time in enumerate(km_times_s):
        km_dist = 1000.0
        speed = km_dist / km_time  # m/s
        steps = km_time
        for step in range(steps):
            rows.append(
                {
                    "elapsed_seconds": elapsed + step,
                    "distance": dist + step * speed,
                    "heart_rate": hr_base + km_idx * 2,
                    "cadence": 170 + km_idx,
                    "altitude": 10.0 + km_idx * 5,
                    "enhanced_altitude": None,
                    "speed": speed,
                }
            )
        elapsed += km_time
        dist += km_dist
    return rows


def test_km_bucket_stats_single_km():
    """Single 1km at 5:00/km (300 s) using exact integer arithmetic."""
    rows = _make_stream_rows([300])
    splits = AICoach._km_bucket_stats(rows)
    assert len(splits) == 1
    assert splits[0]["km"] == 1
    # elapsed_seconds range: 0 to 299 → delta = 299 s
    # distance range: 0 to 996.666... → delta = 996.666... m
    # Instead of guessing the string, just compute the expected value dynamically
    # from the rows generated by _make_stream_rows
    t_delta = rows[-1]["elapsed_seconds"] - rows[0]["elapsed_seconds"]
    d_delta = rows[-1]["distance"] - rows[0]["distance"]
    expected = _pace_from_time_dist(t_delta, d_delta)
    assert splits[0]["pace"] == expected
    assert splits[0]["avg_hr"] is not None
    assert not splits[0]["is_partial"]


def test_km_bucket_stats_multiple_kms():
    """Verify km count and that faster km has lower pace value than slower km."""
    # 300s/km (5:00), 360s/km (6:00), 420s/km (7:00)
    rows = _make_stream_rows([300, 360, 420])
    splits = AICoach._km_bucket_stats(rows)
    assert len(splits) == 3

    # Extract pace as float min/km for comparison
    def _pace_to_float(pace_str: str) -> float:
        m, s = pace_str.replace("/km", "").split(":")
        return int(m) + int(s) / 60

    assert _pace_to_float(splits[0]["pace"]) < _pace_to_float(splits[1]["pace"])
    assert _pace_to_float(splits[1]["pace"]) < _pace_to_float(splits[2]["pace"])


def test_km_bucket_stats_partial_last_km():
    """Last km covering only 400m should be flagged as partial."""
    rows = _make_stream_rows([442])
    # Add a partial km (400m)
    last_t = rows[-1]["elapsed_seconds"]
    last_d = rows[-1]["distance"]
    for i in range(1, 201):
        rows.append(
            {
                "elapsed_seconds": last_t + i,
                "distance": last_d + i * 2.0,  # 2 m/s → 400m in 200s
                "heart_rate": 155,
                "cadence": 172,
                "altitude": 15.0,
                "enhanced_altitude": None,
                "speed": 2.0,
            }
        )
    splits = AICoach._km_bucket_stats(rows)
    assert len(splits) == 2
    assert splits[1]["is_partial"] is True


def test_km_bucket_stats_empty():
    """Empty row list returns empty splits."""
    assert AICoach._km_bucket_stats([]) == []


# ── Plan parsing tests (unchanged, verify still pass) ──────────────


def test_parse_plan_json_valid():
    """Parse a valid JSON plan block from LLM response."""
    text = """Here's your plan!

```json
{
  "start_date": "2026-03-02",
  "end_date": "2026-03-15",
  "weeks": [
    {
      "week_number": 1,
      "workouts": [
        {
          "day": "Monday",
          "date": "2026-03-02",
          "type": "easy_run",
          "description": "Easy recovery run",
          "distance_km": 6.0,
          "duration_min": 36,
          "pace_min_km": 6.0,
          "hr_zone": "Zone 2"
        }
      ]
    }
  ]
}
```"""
    result = AICoach.parse_plan_json(text)
    assert result is not None
    assert result["start_date"] == "2026-03-02"
    assert len(result["weeks"][0]["workouts"]) == 1


def test_parse_plan_json_no_block():
    assert AICoach.parse_plan_json("No JSON here.") is None


def test_parse_plan_json_invalid_json():
    assert AICoach.parse_plan_json("```json\n{ bad json }\n```") is None


def test_plan_json_to_workouts_null_values():
    """Fields set to 'N/A', 'None', null should all become Python None."""
    plan_json = {
        "weeks": [
            {
                "week_number": 1,
                "workouts": [
                    {
                        "date": "2026-03-02",
                        "type": "easy_run",
                        "description": "Easy",
                        "distance_km": "N/A",
                        "duration_min": "None",
                        "pace_min_km": None,
                        "hr_zone": "null",
                    }
                ],
            }
        ]
    }
    workouts = AICoach.plan_json_to_workouts(plan_id=1, plan_json=plan_json)
    assert len(workouts) == 1
    w = workouts[0]
    assert w["target_distance_km"] is None
    assert w["target_duration_min"] is None
    assert w["target_pace_min_km"] is None
    assert w["target_hr_zone"] is None


def test_plan_json_to_workouts_empty():
    assert AICoach.plan_json_to_workouts(plan_id=1, plan_json={}) == []
    assert AICoach.plan_json_to_workouts(plan_id=1, plan_json={"weeks": []}) == []


# ── Fixture: mocked AICoach instance ──────────────────────────────


@pytest.fixture
def mock_coach():
    """AICoach with mocked Gemini client and a MagicMock database."""
    with (
        patch("strava.utils.ai_coach.genai.Client"),
        patch("strava.utils.ai_coach.load_dotenv"),
        patch.dict("os.environ", {"GOOGLE_API_KEY": "test-key"}),
    ):
        db = MagicMock()
        db.get_pr_summary.return_value = []
        db.get_plan_history.return_value = []
        db.get_adherence_by_workout_type.return_value = []
        coach = AICoach(database=db, hr_zones=[145, 164, 174, 188])
    return coach


# ── get_best_efforts tests ─────────────────────────────────────────


def test_get_best_efforts_empty(mock_coach):
    """No PR data should return a helpful message."""
    mock_coach.db.get_pr_summary.return_value = []
    result = mock_coach._tool_get_best_efforts()
    assert "No best effort" in result


def test_get_best_efforts_with_data(mock_coach):
    """PRs are formatted with name, time, pace, and date."""
    mock_coach.db.get_pr_summary.return_value = [
        {
            "effort_name": "5k",
            "distance": 5000.0,
            "elapsed_time": 1200,  # 20:00 → 4:00/km
            "moving_time": 1200,
            "average_heartrate": 172.0,
            "activity_date": "2025-11-10T09:00:00Z",
            "activity_name": "5K Race",
        }
    ]
    result = mock_coach._tool_get_best_efforts()
    assert "5k" in result
    assert "20:00" in result
    assert "4:00/km" in result
    assert "172bpm" in result


# ── get_activity_laps tests ────────────────────────────────────────


def test_get_activity_laps_not_found(mock_coach):
    """Unknown activity_id returns a not-found message."""
    mock_coach._activities_df = pd.DataFrame()
    result = mock_coach._tool_get_activity_laps(activity_id=99999)
    assert "not found" in result.lower()


def test_get_activity_laps_no_laps(mock_coach):
    """Activity with no lap records returns an informative message."""
    mock_coach._activities_df = pd.DataFrame([{"activity_id": 1, "activity_name": "Morning Run"}])
    mock_coach.db.get_activity_laps.return_value = []
    result = mock_coach._tool_get_activity_laps(activity_id=1)
    assert "No lap data" in result


def test_get_activity_laps_with_data(mock_coach):
    """Lap data is formatted with distance, pace, and HR."""
    mock_coach._activities_df = pd.DataFrame(
        [{"activity_id": 1, "activity_name": "Interval Session"}]
    )
    mock_coach.db.get_activity_laps.return_value = [
        {
            "lap_index": 0,
            "distance": 1000.0,
            "moving_time": 240,  # 4:00/km
            "elapsed_time": 240,
            "average_heartrate": 180.0,
            "average_cadence": 185.0,
            "average_speed": 4.17,
        },
        {
            "lap_index": 1,
            "distance": 1000.0,
            "moving_time": 250,
            "elapsed_time": 250,
            "average_heartrate": 182.0,
            "average_cadence": 184.0,
            "average_speed": 4.0,
        },
    ]
    result = mock_coach._tool_get_activity_laps(activity_id=1)
    assert "2 lap(s)" in result
    assert "Lap 1" in result
    assert "Lap 2" in result
    assert "180bpm" in result


# ── get_fitness_trend tests ────────────────────────────────────────


def _make_activities_df(month_offsets_km: list) -> pd.DataFrame:
    """Build a synthetic activities DataFrame with one row per month entry."""
    rows = []
    base = pd.Timestamp.now(tz="UTC")
    for weeks_back, km in month_offsets_km:
        rows.append(
            {
                "activity_id": len(rows) + 1,
                "activity_date": base - pd.Timedelta(weeks=weeks_back),
                "distance": km * 1000,
                "average_heart_rate": 155.0,
                "suffer_score": km * 2,
            }
        )
    return pd.DataFrame(rows)


def test_get_fitness_trend_empty(mock_coach):
    """No activities returns a helpful message."""
    mock_coach._activities_df = pd.DataFrame()
    result = mock_coach._tool_get_fitness_trend()
    assert "No activities" in result


def test_get_fitness_trend_with_data(mock_coach):
    """Monthly breakdown is included in output."""
    mock_coach._activities_df = _make_activities_df([(1, 10), (3, 12), (5, 8)])
    result = mock_coach._tool_get_fitness_trend()
    assert "Monthly fitness trend" in result
    assert "km" in result


def test_get_fitness_trend_building(mock_coach):
    """Trend shows BUILDING when recent month volume is > 10% higher than previous."""
    mock_coach._activities_df = _make_activities_df(
        [(1, 50), (1, 50), (5, 30), (5, 30)]  # recent ~100km vs older ~60km
    )
    result = mock_coach._tool_get_fitness_trend()
    assert "BUILDING" in result


# ── get_plan_adherence tests ───────────────────────────────────────


def test_get_plan_adherence_no_plans(mock_coach):
    """No plans returns an informative message."""
    mock_coach.db.get_plan_history.return_value = []
    result = mock_coach._tool_get_plan_adherence()
    assert "No training plans" in result


def test_get_plan_adherence_with_breakdown(mock_coach):
    """Adherence breakdown by workout type is included in output."""
    mock_coach.db.get_plan_history.return_value = [
        {
            "plan_id": 1,
            "goal": "Sub-4 marathon",
            "start_date": "2026-01-01",
            "end_date": "2026-03-01",
            "status": "active",
            "workout_count": 20,
            "completed_count": 14,
        }
    ]
    mock_coach.db.get_adherence_by_workout_type.return_value = [
        {"workout_type": "easy_run", "total": 12, "completed": 11},
        {"workout_type": "intervals", "total": 8, "completed": 3},
    ]
    result = mock_coach._tool_get_plan_adherence()
    assert "Sub-4 marathon" in result
    assert "Easy Run" in result
    assert "Intervals" in result
    # Good adherence on easy runs → green tick
    assert "✅" in result
    # Poor adherence on intervals → red cross
    assert "❌" in result
